### ISSUE TITLE
How to run the scripts

### ISSUE THREAD

**Issue by hjoab** [JeffBow/AzurePowerShell#11]
I am new to Azure and we need to clone our production resource group to a testing resource group and I found this script you have for just that. But I have idea how to run it at Azure Cloud.

**Comment by JeffBow** [comment]
All of the scripts have contextual help.  For cloning, use **Get-Help .\Clone-AzureRMresourceGroup.ps1 -full** in PowerShell to see the full usage with examples.

**Comment by hjoab** [comment]
I know about cloning. I used GitHub for windows.  I have Azure Cloud. I am running Powershell and I thought it was as simple as to upload the file into the file sharing  and call it. But it says the file does not exist???? 

tnx for your help.

**Comment by hjoab** [comment]
I have an Pay-As-You-Go account. I t looks I cannot run it with this type of account. Is that right?

**Comment by MarvinWds** [comment]
Good evening Otto.

It is best if you run this script from a local workstation in ISE (As an
administrator) or from a powershell prompt.
Navigate to the location of the script, use loginazurerm to login to Azure
and run the script using the variables for the source resource group and
the destination resource group.
Remember that all resources on the source resource group need the be shut
down in order to copy the resource group to the new resource group.

Regards, Marvin Woods

Op vr 13 apr. 2018 22:01 schreef Holger Otto Andre <notifications@github.com

**Comment by hjoab** [comment]
Hello Marvin

Thanks for your help. I was able to run the script following your instructions, but I am having similar issues with disks creation and other. I will reply in the other issue
 " error at new storage account creation when cloning resource group in same subscription"
